package com.mynikatech.memgine.component.organizationaccess

import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.Test
import kotlin.test.assertContains

class OrganizationAccessSqlContractTest {
    private val migration = Files.readString(
        Path.of("..", "DB", "liquibase", "sql", "083-organization-users-access.sql")
    )

    @Test
    fun `final admin mutations use the same organization transaction lock`() {
        val lock = "pg_advisory_xact_lock(hashtextextended('organization-admin:' || p_organization_id, 0))"
        assertContains(migration, lock)
        assertContains(migration.substringAfter(lock), lock)
    }

    @Test
    fun `fixed POS includes an admin only when also an active configured counter operator`() {
        val pos = migration.substringAfter("CREATE OR REPLACE FUNCTION \"\${schemaName}\".pos_eligible_staff")
        assertContains(pos, "JOIN \"\${schemaName}\".staff st")
        assertContains(pos, "sts.status_code = 'ACTIVE'")
        assertContains(pos, "JOIN \"\${schemaName}\".staff_pin_credentials pc")
        assertContains(pos, "'COUNTER_ACCESS'")
    }

    @Test
    fun `fixed POS excludes inactive organization users and global users`() {
        val pos = migration.substringAfter("CREATE OR REPLACE FUNCTION \"\${schemaName}\".pos_eligible_staff")
        assertContains(pos, "ous.status_code = 'ACTIVE'")
        assertContains(pos, "us.status_code = 'ACTIVE'")
    }

    @Test
    fun `counter operator staff codes are generated by the database`() {
        val counterOperator = migration.substringAfter(
            "CREATE OR REPLACE FUNCTION \"\${schemaName}\".organization_access_set_counter_operator"
        )
        assertContains(counterOperator, "pg_advisory_xact_lock(hashtext(p_organization_id || ':' || v_store_id))")
        assertContains(counterOperator, "v_store_code || '-STAFF-' || lpad(v_next_staff_number::text, 3, '0')")
        assertContains(counterOperator, "A primary store is required to enable a new Counter Operator")
    }
}
