databaseChangeLog:
  - changeSet:
      id: 050-2f-notification-configuration-functions
      author: mynikatech
      runOnChange: true
      changes:
        - sqlFile:
            path: ../sql/050-2f-notification-configuration-functions.sql
            relativeToChangelogFile: true
            splitStatements: false
            stripComments: false
