databaseChangeLog:
  - changeSet:
      id: 103-configurable-redemption-expiry
      author: mynikatech
      changes:
        - sqlFile:
            path: ../sql/103-configurable-redemption-expiry.sql
            relativeToChangelogFile: true
            splitStatements: false
            stripComments: false
