-- Opaque, short-lived QR references for authoritative redemption transactions.
-- The raw reference is generated by the server and is never stored here.
-- OTP already establishes the canonical convention for timestamp without time
-- zone: UTC local timestamps via CURRENT_TIMESTAMP AT TIME ZONE 'UTC'. This
-- migration applies that convention to consolidated redemption expiry paths.

CREATE TABLE IF NOT EXISTS "${schemaName}".redemption_transaction_qr (
    redemption_transaction_qr_id varchar(64) PRIMARY KEY,
    organization_id varchar(64) NOT NULL REFERENCES "${schemaName}".organization(organization_id),
    redemption_transaction_id varchar(64) NOT NULL REFERENCES "${schemaName}".redemption_transaction(redemption_transaction_id) ON DELETE CASCADE,
    token_hash char(64) NOT NULL UNIQUE,
    expires_at timestamp without time zone NOT NULL,
    revoked_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    created_by varchar(64) NOT NULL REFERENCES "${schemaName}"."user"(user_id),
    updated_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_by varchar(64) NOT NULL REFERENCES "${schemaName}"."user"(user_id),
    version_no integer NOT NULL DEFAULT 1,
    CONSTRAINT ck_redemption_transaction_qr_expiry CHECK (expires_at > created_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_redemption_transaction_qr_active_transaction
    ON "${schemaName}".redemption_transaction_qr(redemption_transaction_id)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_redemption_transaction_qr_resolution
    ON "${schemaName}".redemption_transaction_qr(organization_id, token_hash)
    WHERE revoked_at IS NULL;

-- 098 is already applied. Replace only the three functions which create or
-- compare redemption expiry, keeping its transaction and eligibility logic.
CREATE OR REPLACE FUNCTION "${schemaName}".create_redemption_transaction_internal(
 p_organization_id varchar,p_store_id varchar,p_staff_id varchar,p_subscription_id varchar,p_benefit_ids varchar[],p_offer_ids varchar[],p_redemption_method varchar,p_actor_user_id varchar
) RETURNS TABLE("transactionId" varchar,"transactionNumber" varchar,status varchar,"expiresAt" text) LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, "${schemaName}" AS $function$
DECLARE
 v_id varchar(64); v_number varchar(64); v_item varchar(64); v_benefit varchar; v_offer varchar; v_reason text; v_seq bigint;
 v_now timestamp without time zone := CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
 v_expires_at timestamp without time zone;
BEGIN
 IF COALESCE(cardinality(p_benefit_ids),0)+COALESCE(cardinality(p_offer_ids),0)=0 THEN RAISE EXCEPTION 'Select one or more benefits or offers' USING ERRCODE='22023'; END IF;
 IF (p_benefit_ids IS NOT NULL AND cardinality(p_benefit_ids)<> (SELECT count(DISTINCT x) FROM unnest(p_benefit_ids)x)) OR (p_offer_ids IS NOT NULL AND cardinality(p_offer_ids)<> (SELECT count(DISTINCT x) FROM unnest(p_offer_ids)x)) THEN RAISE EXCEPTION 'Select distinct redemption items' USING ERRCODE='22023'; END IF;
 PERFORM 1 FROM subscriptions s JOIN organization_user ou ON ou.organization_user_id=s.organization_user_id WHERE s.subscription_id=p_subscription_id AND ou.organization_id=p_organization_id AND NOT s.is_deleted AND NOT ou.is_deleted FOR UPDATE OF s; IF NOT FOUND THEN RAISE EXCEPTION 'Subscription not found' USING ERRCODE='P0002'; END IF;
 FOREACH v_benefit IN ARRAY COALESCE(p_benefit_ids,ARRAY[]::varchar[]) LOOP v_reason:=counter_benefit_rejection(p_organization_id,p_subscription_id,v_benefit); IF v_reason IS NOT NULL THEN RAISE EXCEPTION '%',v_reason USING ERRCODE='23505'; END IF; END LOOP;
 FOREACH v_offer IN ARRAY COALESCE(p_offer_ids,ARRAY[]::varchar[]) LOOP v_reason:=counter_offer_rejection(p_organization_id,p_subscription_id,v_offer,p_store_id); IF v_reason IS NOT NULL THEN RAISE EXCEPTION '%',v_reason USING ERRCODE='23505'; END IF; END LOOP;
 v_id:=generate_runtime_id('RTX'); v_seq:=next_business_sequence('REDEMPTION_TRANSACTION',p_organization_id); v_number:=('RTX_'||lpad(v_seq::text,6,'0'))::varchar(64);
 v_expires_at := v_now + interval '10 minutes';
 INSERT INTO redemption_transaction(redemption_transaction_id,redemption_transaction_number,organization_id,subscription_id,store_id,staff_id,redemption_method,status,expires_at,created_by,updated_by) VALUES(v_id,v_number,p_organization_id,p_subscription_id,p_store_id,p_staff_id,p_redemption_method,'PENDING',v_expires_at,p_actor_user_id,p_actor_user_id);
 FOREACH v_benefit IN ARRAY COALESCE(p_benefit_ids,ARRAY[]::varchar[]) LOOP v_item:=generate_runtime_id('RTI'); INSERT INTO redemption_transaction_item(redemption_transaction_item_id,redemption_transaction_id,item_type,benefit_id,created_by,updated_by) VALUES(v_item,v_id,'BENEFIT',v_benefit,p_actor_user_id,p_actor_user_id); END LOOP;
 FOREACH v_offer IN ARRAY COALESCE(p_offer_ids,ARRAY[]::varchar[]) LOOP v_item:=generate_runtime_id('RTI'); INSERT INTO redemption_transaction_item(redemption_transaction_item_id,redemption_transaction_id,item_type,offer_id,created_by,updated_by) VALUES(v_item,v_id,'OFFER',v_offer,p_actor_user_id,p_actor_user_id); END LOOP;
 RETURN QUERY SELECT v_id,v_number,'PENDING'::varchar,v_expires_at::text;
END; $function$;

CREATE OR REPLACE FUNCTION "${schemaName}".validate_redemption_transaction(p_transaction_id varchar,p_organization_id varchar,p_store_id varchar,p_staff_id varchar,p_actor_user_id varchar)
RETURNS TABLE("itemId" varchar,"itemType" varchar,"benefitId" varchar,"offerId" varchar,eligible boolean,"rejectionReason" text) LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, "${schemaName}" AS $function$
DECLARE r record; v_reason text; v_sub varchar; v_status varchar; v_expires_at timestamp; v_now timestamp without time zone := CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
BEGIN
 IF NOT counter_can_operate(p_organization_id,p_store_id,p_staff_id,p_actor_user_id) THEN RAISE EXCEPTION 'Counter store or staff context is not permitted' USING ERRCODE='42501'; END IF;
 SELECT subscription_id,status,expires_at INTO v_sub,v_status,v_expires_at FROM redemption_transaction WHERE redemption_transaction_id=p_transaction_id AND organization_id=p_organization_id; IF v_sub IS NULL THEN RAISE EXCEPTION 'Redemption transaction not found' USING ERRCODE='P0002'; END IF; IF v_status<>'PENDING' THEN RAISE EXCEPTION 'Redemption transaction is not pending' USING ERRCODE='23505'; END IF; IF v_expires_at IS NOT NULL AND v_expires_at<=v_now THEN RAISE EXCEPTION 'Redemption transaction has expired' USING ERRCODE='23505'; END IF;
 FOR r IN SELECT * FROM redemption_transaction_item WHERE redemption_transaction_id=p_transaction_id ORDER BY created_at LOOP v_reason:=CASE WHEN r.item_type='BENEFIT' THEN counter_benefit_rejection(p_organization_id,v_sub,r.benefit_id) ELSE counter_offer_rejection(p_organization_id,v_sub,r.offer_id,p_store_id) END; RETURN QUERY SELECT r.redemption_transaction_item_id,r.item_type,r.benefit_id,r.offer_id,v_reason IS NULL,v_reason; END LOOP;
END; $function$;

CREATE OR REPLACE FUNCTION "${schemaName}".execute_redemption_transaction(p_transaction_id varchar,p_organization_id varchar,p_store_id varchar,p_staff_id varchar,p_actor_user_id varchar)
RETURNS TABLE("transactionId" varchar,"transactionNumber" varchar,status varchar,"completedAt" text) LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, "${schemaName}" AS $function$
DECLARE t record; i record; v_reason text; v_redemption varchar(64); v_number varchar(64); v_offer_redemption varchar(64); v_seq bigint; v_success varchar; v_now timestamp without time zone := CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
BEGIN
 IF NOT counter_can_operate(p_organization_id,p_store_id,p_staff_id,p_actor_user_id) THEN RAISE EXCEPTION 'Counter store or staff context is not permitted' USING ERRCODE='42501'; END IF;
 SELECT * INTO t FROM redemption_transaction WHERE redemption_transaction_id=p_transaction_id AND organization_id=p_organization_id FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Redemption transaction not found' USING ERRCODE='P0002'; END IF;
 IF t.status<>'PENDING' THEN RAISE EXCEPTION 'Redemption transaction cannot be executed' USING ERRCODE='23505'; END IF; IF t.expires_at IS NOT NULL AND t.expires_at<=v_now THEN RAISE EXCEPTION 'Redemption transaction has expired' USING ERRCODE='23505'; END IF;
 PERFORM 1 FROM subscriptions WHERE subscription_id=t.subscription_id FOR UPDATE;
 FOR i IN SELECT * FROM redemption_transaction_item WHERE redemption_transaction_id=p_transaction_id FOR UPDATE LOOP v_reason:=CASE WHEN i.item_type='BENEFIT' THEN counter_benefit_rejection(p_organization_id,t.subscription_id,i.benefit_id) ELSE counter_offer_rejection(p_organization_id,t.subscription_id,i.offer_id,p_store_id) END; IF v_reason IS NOT NULL THEN RAISE EXCEPTION '%',v_reason USING ERRCODE='23505'; END IF; END LOOP;
 SELECT es.entity_status_id INTO v_success FROM entity_status es JOIN entity_type et ON et.entity_type_id=es.entity_type_id JOIN statuses s ON s.status_id=es.status_id WHERE et.entity_type_code='REDEMPTION' AND s.status_code='SUCCESS' AND es.is_active;
 FOR i IN SELECT * FROM redemption_transaction_item WHERE redemption_transaction_id=p_transaction_id FOR UPDATE LOOP
   IF i.item_type='BENEFIT' THEN v_redemption:=generate_runtime_id('RDM'); v_seq:=next_business_sequence('REDEMPTION',t.subscription_id); SELECT (subscription_number||'_RDM_'||lpad(v_seq::text,3,'0'))::varchar(64) INTO v_number FROM subscriptions WHERE subscription_id=t.subscription_id; INSERT INTO redemptions(redemption_id,redemption_number,subscription_id,benefit_id,store_id,staff_id,redemption_status_id,created_by,updated_by) VALUES(v_redemption,v_number,t.subscription_id,i.benefit_id,p_store_id,p_staff_id,v_success,p_actor_user_id,p_actor_user_id); UPDATE redemption_transaction_item SET redemption_id=v_redemption,status='SUCCESS',updated_at=CURRENT_TIMESTAMP,updated_by=p_actor_user_id,version_no=version_no+1 WHERE redemption_transaction_item_id=i.redemption_transaction_item_id;
   ELSE v_offer_redemption:=generate_runtime_id('ORD'); INSERT INTO offer_redemptions(offer_redemption_id,redemption_transaction_id,redemption_transaction_item_id,organization_id,subscription_id,offer_id,store_id,staff_id,created_by,updated_by) VALUES(v_offer_redemption,p_transaction_id,i.redemption_transaction_item_id,p_organization_id,t.subscription_id,i.offer_id,p_store_id,p_staff_id,p_actor_user_id,p_actor_user_id); UPDATE redemption_transaction_item SET offer_redemption_id=v_offer_redemption,status='SUCCESS',updated_at=CURRENT_TIMESTAMP,updated_by=p_actor_user_id,version_no=version_no+1 WHERE redemption_transaction_item_id=i.redemption_transaction_item_id; END IF;
 END LOOP;
 UPDATE redemption_transaction SET status='SUCCESS',store_id=p_store_id,staff_id=p_staff_id,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,updated_by=p_actor_user_id,version_no=version_no+1 WHERE redemption_transaction_id=p_transaction_id;
 RETURN QUERY SELECT t.redemption_transaction_id,t.redemption_transaction_number,'SUCCESS'::varchar,CURRENT_TIMESTAMP::text;
END; $function$;

CREATE OR REPLACE FUNCTION "${schemaName}".issue_customer_redemption_transaction_qr(
    p_organization_id varchar,
    p_transaction_id varchar,
    p_token_hash varchar,
    p_actor_user_id varchar
)
RETURNS TABLE("qrId" varchar, "transactionNumber" varchar, "expiresAt" text)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, "${schemaName}"
AS $function$
DECLARE
    v_transaction record;
    v_qr_id varchar(64);
BEGIN
    IF p_token_hash !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'Invalid redemption QR reference' USING ERRCODE = '22023';
    END IF;

    SELECT t.* INTO v_transaction
      FROM redemption_transaction t
      JOIN subscriptions s ON s.subscription_id = t.subscription_id AND NOT s.is_deleted
      JOIN organization_user ou ON ou.organization_user_id = s.organization_user_id AND NOT ou.is_deleted
      JOIN organization_user_types outype ON outype.organization_user_type_id = ou.organization_user_type_id
      JOIN entity_status oustatus ON oustatus.entity_status_id = ou.organization_user_status_id
      JOIN statuses oustatus_code ON oustatus_code.status_id = oustatus.status_id
     WHERE t.redemption_transaction_id = p_transaction_id
       AND t.organization_id = p_organization_id
       AND ou.organization_id = p_organization_id
       AND ou.user_id = p_actor_user_id
       AND outype.organization_user_type_code = 'CUSTOMER'
       AND oustatus_code.status_code = 'ACTIVE'
       AND t.status = 'PENDING'
       AND t.expires_at > (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
     FOR UPDATE OF t;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Redemption transaction is unavailable' USING ERRCODE = '42501';
    END IF;

    UPDATE redemption_transaction_qr
       SET revoked_at = CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
           updated_at = CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
           updated_by = p_actor_user_id,
           version_no = version_no + 1
     WHERE redemption_transaction_id = p_transaction_id
       AND revoked_at IS NULL;

    v_qr_id := generate_runtime_id('RQR');
    INSERT INTO redemption_transaction_qr (
        redemption_transaction_qr_id, organization_id, redemption_transaction_id,
        token_hash, expires_at, created_by, updated_by
    ) VALUES (
        v_qr_id, p_organization_id, p_transaction_id, p_token_hash,
        v_transaction.expires_at, p_actor_user_id, p_actor_user_id
    );

    RETURN QUERY SELECT v_qr_id, v_transaction.redemption_transaction_number,
        v_transaction.expires_at::text;
END;
$function$;

CREATE OR REPLACE FUNCTION "${schemaName}".resolve_counter_redemption_transaction_qr(
    p_organization_id varchar,
    p_store_id varchar,
    p_staff_id varchar,
    p_token_hash varchar,
    p_actor_user_id varchar
)
RETURNS TABLE("transactionId" varchar, "transactionNumber" varchar, status varchar, "expiresAt" text)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, "${schemaName}"
AS $function$
BEGIN
    IF NOT counter_can_operate(p_organization_id, p_store_id, p_staff_id, p_actor_user_id) THEN
        RAISE EXCEPTION 'Counter store or staff context is not permitted' USING ERRCODE = '42501';
    END IF;

    RETURN QUERY
    SELECT t.redemption_transaction_id, t.redemption_transaction_number,
           t.status, t.expires_at::text
      FROM redemption_transaction_qr q
      JOIN redemption_transaction t
        ON t.redemption_transaction_id = q.redemption_transaction_id
     WHERE q.organization_id = p_organization_id
       AND q.token_hash = p_token_hash
       AND q.revoked_at IS NULL
       AND q.expires_at > (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
       AND t.organization_id = p_organization_id
       AND t.status = 'PENDING'
       AND t.expires_at > (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invalid redemption QR reference' USING ERRCODE = 'P0002';
    END IF;
END;
$function$;

-- A transaction can also reach a non-pending state outside the QR resolver.
-- Revoke its active QR as defense in depth; failed validation does not change
-- transaction status and therefore leaves the QR valid until expiry.
CREATE OR REPLACE FUNCTION "${schemaName}".revoke_redemption_transaction_qr_on_completion()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, "${schemaName}"
AS $function$
BEGIN
    IF OLD.status = 'PENDING' AND NEW.status <> 'PENDING' THEN
        UPDATE redemption_transaction_qr
           SET revoked_at = CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
               updated_at = CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
               updated_by = NEW.updated_by,
               version_no = version_no + 1
         WHERE redemption_transaction_id = NEW.redemption_transaction_id
           AND revoked_at IS NULL;
    END IF;
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_revoke_redemption_transaction_qr_on_completion
    ON "${schemaName}".redemption_transaction;
CREATE TRIGGER trg_revoke_redemption_transaction_qr_on_completion
AFTER UPDATE OF status ON "${schemaName}".redemption_transaction
FOR EACH ROW EXECUTE FUNCTION "${schemaName}".revoke_redemption_transaction_qr_on_completion();

REVOKE ALL ON FUNCTION "${schemaName}".issue_customer_redemption_transaction_qr(varchar, varchar, varchar, varchar) FROM PUBLIC;
REVOKE ALL ON FUNCTION "${schemaName}".resolve_counter_redemption_transaction_qr(varchar, varchar, varchar, varchar, varchar) FROM PUBLIC;
REVOKE ALL ON FUNCTION "${schemaName}".revoke_redemption_transaction_qr_on_completion() FROM PUBLIC;

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${appRole}') THEN
        GRANT EXECUTE ON FUNCTION "${schemaName}".issue_customer_redemption_transaction_qr(varchar, varchar, varchar, varchar) TO "${appRole}";
        GRANT EXECUTE ON FUNCTION "${schemaName}".resolve_counter_redemption_transaction_qr(varchar, varchar, varchar, varchar, varchar) TO "${appRole}";
    END IF;
END;
$grant$;
