MEMGINE_DB_URL=jdbc:postgresql://127.0.0.1:5432/memgine_dev
MEMGINE_DB_USER=memgine_app_dev
MEMGINE_DB_PASSWORD=m3mg1ne@applocal
MEMGINE_DB_SCHEMA=memginedev
MEMGINE_DB_POOL_SIZE=10
MEMGINE_SERVER_PORT=8082