worker_processes auto;
error_log /var/log/nginx/memgine-dev-error.log warn;
pid /run/nginx-memgine-dev.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    include conf.d/*.conf;
}